export const GREEN_APPOINTMENT_COLOR = "#71CDB2";

export const GRID_STATE_OPEN_COLOR = "#6AB04C";
export const GRID_STATE_SUSPENDED_COLOR = "#F0932B";
export const GRID_STATE_CLOSED_COLOR = "#EB4D4B";

export const USER_STATUS_AVAILABLE_COLOR = "#6AB04C";
export const USER_STATUS_UNAVAILABLE_COLOR = "#EB4D4B";
