GRANT USAGE ON SCHEMA appointments TO "apps";
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA appointments TO "apps";
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA appointments TO "apps";
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA appointments TO "apps";
ALTER DEFAULT PRIVILEGES IN SCHEMA appointments GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON TABLES TO "apps";
ALTER DEFAULT PRIVILEGES IN SCHEMA appointments GRANT EXECUTE ON FUNCTIONS TO "apps";
ALTER DEFAULT PRIVILEGES IN SCHEMA appointments GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO "apps";