import dayjs from "dayjs";

import { USER_STATUS } from "./enums";
import { UserCardInfos } from "./types";

// Fonction pour mélanger un tableau de manière aléatoire
const shuffleArray = <T>(array: T[]): T[] => {
  return array.sort(() => Math.random() - 0.5);
};

export const mock: UserCardInfos[] = shuffleArray([
  {
    userId: "1",
    picture: null,
    displayName: "Alice Dupont",
    functions: "Médecin généraliste",
    lastAppointmentDate: dayjs().subtract(2, "days"),
    status: USER_STATUS.AVAILABLE,
  },
  {
    userId: "2",
    picture: null,
    displayName: "Bob Martin looooooooooooooooooooooooong",
    functions: "Psychologue looooooooooooooooooooooooong",
    lastAppointmentDate: null,
    status: USER_STATUS.UNAVAILABLE,
  },
  {
    userId: "3",
    picture: null,
    displayName: "Charlie Bernard looooooooooooooooooooooong",
    functions: "Chirurgien",
    lastAppointmentDate: dayjs().subtract(1, "week"),
    status: USER_STATUS.AVAILABLE,
  },
  {
    userId: "4",
    picture: null,
    displayName: "Denise Laurent",
    functions: "Infirmière",
    lastAppointmentDate: null,
    status: USER_STATUS.UNAVAILABLE,
  },
  {
    userId: "5",
    picture: null,
    displayName: "Edgar Faure",
    functions: "Dentiste",
    lastAppointmentDate: dayjs().subtract(2, "weeks"),
    status: USER_STATUS.AVAILABLE,
  },
  {
    userId: "6",
    picture: null,
    displayName: "Françoise Delacour",
    functions: "Kiné",
    lastAppointmentDate: dayjs().subtract(4, "days"),
    status: USER_STATUS.UNAVAILABLE,
  },
  {
    userId: "7",
    picture: null,
    displayName: "Georges Dupuis",
    functions: "Orthopédiste",
    lastAppointmentDate: null,
    status: USER_STATUS.AVAILABLE,
  },
  {
    userId: "8",
    picture: null,
    displayName: "Hélène Girard",
    functions: "Cardiologue",
    lastAppointmentDate: dayjs().subtract(10, "days"),
    status: USER_STATUS.UNAVAILABLE,
  },
  {
    userId: "9",
    picture: null,
    displayName: "Ibrahim Benamar",
    functions: "Neurologue",
    lastAppointmentDate: null,
    status: USER_STATUS.AVAILABLE,
  },
  {
    userId: "10",
    picture: null,
    displayName: "Julie Bertin",
    functions: "Psychiatre",
    lastAppointmentDate: dayjs().subtract(2, "days"),
    status: USER_STATUS.UNAVAILABLE,
  },
  {
    userId: "11",
    picture: null,
    displayName: "Karim Slaoui",
    functions: "Anesthésiste",
    lastAppointmentDate: dayjs().subtract(5, "days"),
    status: USER_STATUS.AVAILABLE,
  },
  {
    userId: "12",
    picture: null,
    displayName: "Laura Blanc",
    functions: "Radiologue",
    lastAppointmentDate: null,
    status: USER_STATUS.UNAVAILABLE,
  },
  {
    userId: "13",
    picture: null,
    displayName: "Moussa Koné",
    functions: "Urologue",
    lastAppointmentDate: dayjs().subtract(1, "month"),
    status: USER_STATUS.AVAILABLE,
  },
  {
    userId: "14",
    picture: null,
    displayName: "Nadia El Fassi",
    functions: "Pédiatre",
    lastAppointmentDate: null,
    status: USER_STATUS.UNAVAILABLE,
  },
  {
    userId: "15",
    picture: null,
    displayName: "Olivier Henry",
    functions: "Dermatologue",
    lastAppointmentDate: dayjs().subtract(3, "days"),
    status: USER_STATUS.AVAILABLE,
  },
  {
    userId: "16",
    picture: null,
    displayName: "Patricia Robert",
    functions: "Nutritionniste",
    lastAppointmentDate: null,
    status: USER_STATUS.UNAVAILABLE,
  },
  {
    userId: "17",
    picture: null,
    displayName: "Quentin Petit",
    functions: "Pharmacien",
    lastAppointmentDate: dayjs().subtract(9, "days"),
    status: USER_STATUS.AVAILABLE,
  },
  {
    userId: "18",
    picture: null,
    displayName: "Rania Haddad",
    functions: "Rhumatologue",
    lastAppointmentDate: dayjs().subtract(11, "days"),
    status: USER_STATUS.UNAVAILABLE,
  },
  {
    userId: "19",
    picture: null,
    displayName: "Sébastien Leclerc",
    functions: "Gynécologue",
    lastAppointmentDate: dayjs().subtract(3, "weeks"),
    status: USER_STATUS.AVAILABLE,
  },
  {
    userId: "20",
    picture: null,
    displayName: "Thérèse Moulin",
    functions: "Endocrinologue",
    lastAppointmentDate: null,
    status: USER_STATUS.UNAVAILABLE,
  },
  {
    userId: "21",
    picture: null,
    displayName: "Ugo Martin",
    functions: "Pneumologue",
    lastAppointmentDate: dayjs().subtract(1, "week"),
    status: USER_STATUS.AVAILABLE,
  },
  {
    userId: "22",
    picture: null,
    displayName: "Valérie Dubois",
    functions: "Oncologue",
    lastAppointmentDate: dayjs().subtract(5, "days"),
    status: USER_STATUS.UNAVAILABLE,
  },
  {
    userId: "23",
    picture: null,
    displayName: "William Faure",
    functions: "Hématologue",
    lastAppointmentDate: null,
    status: USER_STATUS.AVAILABLE,
  },
  {
    userId: "24",
    picture: null,
    displayName: "Xavier Martin",
    functions: "Ophtalmologue",
    lastAppointmentDate: dayjs().subtract(1, "month"),
    status: USER_STATUS.UNAVAILABLE,
  },
  {
    userId: "25",
    picture: null,
    displayName: "Yasmine Abou",
    functions: "Néphrologue",
    lastAppointmentDate: dayjs().subtract(2, "weeks"),
    status: USER_STATUS.AVAILABLE,
  },
  {
    userId: "26",
    picture: null,
    displayName: "Zacharie Laurent",
    functions: "Chirurgien vasculaire",
    lastAppointmentDate: null,
    status: USER_STATUS.UNAVAILABLE,
  },
  {
    userId: "27",
    picture: null,
    displayName: "Zoé Dupuis",
    functions: "Chirurgien orthopédiste",
    lastAppointmentDate: dayjs().subtract(2, "days"),
    status: USER_STATUS.AVAILABLE,
  },
  {
    userId: "28",
    picture: null,
    displayName: "Aurélie Girard",
    functions: "Cardiologue",
    lastAppointmentDate: null,
    status: USER_STATUS.UNAVAILABLE,
  },
  {
    userId: "29",
    picture: null,
    displayName: "Baptiste Benamar",
    functions: "Neurologue",
    lastAppointmentDate: dayjs().subtract(1, "week"),
    status: USER_STATUS.AVAILABLE,
  },
  {
    userId: "30",
    picture: null,
    displayName: "Céline Bertin",
    functions: "Psychiatre",
    lastAppointmentDate: dayjs().subtract(2, "days"),
    status: USER_STATUS.UNAVAILABLE,
  },
  {
    userId: "31",
    picture: null,
    displayName: "Dylan Slaoui",
    functions: "Anesthésiste",
    lastAppointmentDate: dayjs().subtract(5, "days"),
    status: USER_STATUS.AVAILABLE,
  },
  {
    userId: "32",
    picture: null,
    displayName: "Emma Blanc",
    functions: "Radiologue",
    lastAppointmentDate: null,
    status: USER_STATUS.UNAVAILABLE,
  },
  {
    userId: "33",
    picture: null,
    displayName: "Florian Koné",
    functions: "Urologue",
    lastAppointmentDate: dayjs().subtract(1, "month"),
    status: USER_STATUS.AVAILABLE,
  },
  {
    userId: "34",
    picture: null,
    displayName: "Géraldine El Fassi",
    functions: "Pédiatre",
    lastAppointmentDate: null,
    status: USER_STATUS.UNAVAILABLE,
  },
  {
    userId: "35",
    picture: null,
    displayName: "Hugo Henry",
    functions: "Dermatologue",
    lastAppointmentDate: dayjs().subtract(3, "days"),
    status: USER_STATUS.AVAILABLE,
  },
  {
    userId: "36",
    picture: null,
    displayName: "Inès Robert",
    functions: "Nutritionniste",
    lastAppointmentDate: null,
    status: USER_STATUS.UNAVAILABLE,
  },
  {
    userId: "37",
    picture: null,
    displayName: "Jérémy Petit",
    functions: "Pharmacien",
    lastAppointmentDate: dayjs().subtract(9, "days"),
    status: USER_STATUS.AVAILABLE,
  },
  {
    userId: "38",
    picture: null,
    displayName: "Karine Haddad",
    functions: "Rhumatologue",
    lastAppointmentDate: dayjs().subtract(11, "days"),
    status: USER_STATUS.UNAVAILABLE,
  },
  {
    userId: "39",
    picture: null,
    displayName: "Léa Leclerc",
    functions: "Gynécologue",
    lastAppointmentDate: dayjs().subtract(3, "weeks"),
    status: USER_STATUS.AVAILABLE,
  },
  {
    userId: "40",
    picture: null,
    displayName: "Mathieu Moulin",
    functions: "Endocrinologue",
    lastAppointmentDate: null,
    status: USER_STATUS.UNAVAILABLE,
  },
  {
    userId: "41",
    picture: null,
    displayName: "Nathalie Martin",
    functions: "Pneumologue",
    lastAppointmentDate: dayjs().subtract(1, "week"),
    status: USER_STATUS.AVAILABLE,
  },
  {
    userId: "42",
    picture: null,
    displayName: "Olivier Dubois",
    functions: "Oncologue",
    lastAppointmentDate: dayjs().subtract(5, "days"),
    status: USER_STATUS.UNAVAILABLE,
  },
  {
    userId: "43",
    picture: null,
    displayName: "Paul Faure",
    functions: "Hématologue",
    lastAppointmentDate: null,
    status: USER_STATUS.AVAILABLE,
  },
  {
    userId: "44",
    picture: null,
    displayName: "Quentin Martin",
    functions: "Ophtalmologue",
    lastAppointmentDate: dayjs().subtract(1, "month"),
    status: USER_STATUS.UNAVAILABLE,
  },
  {
    userId: "45",
    picture: null,
    displayName: "Rania Abou",
    functions: "Néphrologue",
    lastAppointmentDate: dayjs().subtract(2, "weeks"),
    status: USER_STATUS.AVAILABLE,
  },
]);

export const NUMBER_MORE_USERS = 20;
export const initialUsers = mock.slice(0, NUMBER_MORE_USERS);
