import dayjs from "dayjs";

import { USER_STATUS } from "./enums";
import { UserCardInfos } from "./types";

// Fonction pour mélanger un tableau de manière aléatoire
const shuffleArray = <T>(array: T[]): T[] => {
  return array.sort(() => Math.random() - 0.5);
};

export const mock: UserCardInfos[] = shuffleArray([
  {
    userId: "1",
    profilePicture: null,
    displayName: "Alice Dupont",
    profession: "Médecin généraliste",
    lastAppointment: dayjs().subtract(2, "days"),
    status: USER_STATUS.AVAILABLE,
  },
  {
    userId: "2",
    profilePicture: null,
    displayName: "Bob Martin looooooooooooooooooooooooong",
    profession: "Psychologue looooooooooooooooooooooooong",
    lastAppointment: null,
    status: USER_STATUS.UNAVAILABLE,
  },
  {
    userId: "3",
    profilePicture: null,
    displayName: "Charlie Bernard looooooooooooooooooooooong",
    profession: "Chirurgien",
    lastAppointment: dayjs().subtract(1, "week"),
    status: USER_STATUS.AVAILABLE,
  },
  {
    userId: "4",
    profilePicture: null,
    displayName: "Denise Laurent",
    profession: "Infirmière",
    lastAppointment: null,
    status: USER_STATUS.UNAVAILABLE,
  },
  {
    userId: "5",
    profilePicture: null,
    displayName: "Edgar Faure",
    profession: "Dentiste",
    lastAppointment: dayjs().subtract(2, "weeks"),
    status: USER_STATUS.AVAILABLE,
  },
  {
    userId: "6",
    profilePicture: null,
    displayName: "Françoise Delacour",
    profession: "Kiné",
    lastAppointment: dayjs().subtract(4, "days"),
    status: USER_STATUS.UNAVAILABLE,
  },
  {
    userId: "7",
    profilePicture: null,
    displayName: "Georges Dupuis",
    profession: "Orthopédiste",
    lastAppointment: null,
    status: USER_STATUS.AVAILABLE,
  },
  {
    userId: "8",
    profilePicture: null,
    displayName: "Hélène Girard",
    profession: "Cardiologue",
    lastAppointment: dayjs().subtract(10, "days"),
    status: USER_STATUS.UNAVAILABLE,
  },
  {
    userId: "9",
    profilePicture: null,
    displayName: "Ibrahim Benamar",
    profession: "Neurologue",
    lastAppointment: null,
    status: USER_STATUS.AVAILABLE,
  },
  {
    userId: "10",
    profilePicture: null,
    displayName: "Julie Bertin",
    profession: "Psychiatre",
    lastAppointment: dayjs().subtract(2, "days"),
    status: USER_STATUS.UNAVAILABLE,
  },
  {
    userId: "11",
    profilePicture: null,
    displayName: "Karim Slaoui",
    profession: "Anesthésiste",
    lastAppointment: dayjs().subtract(5, "days"),
    status: USER_STATUS.AVAILABLE,
  },
  {
    userId: "12",
    profilePicture: null,
    displayName: "Laura Blanc",
    profession: "Radiologue",
    lastAppointment: null,
    status: USER_STATUS.UNAVAILABLE,
  },
  {
    userId: "13",
    profilePicture: null,
    displayName: "Moussa Koné",
    profession: "Urologue",
    lastAppointment: dayjs().subtract(1, "month"),
    status: USER_STATUS.AVAILABLE,
  },
  {
    userId: "14",
    profilePicture: null,
    displayName: "Nadia El Fassi",
    profession: "Pédiatre",
    lastAppointment: null,
    status: USER_STATUS.UNAVAILABLE,
  },
  {
    userId: "15",
    profilePicture: null,
    displayName: "Olivier Henry",
    profession: "Dermatologue",
    lastAppointment: dayjs().subtract(3, "days"),
    status: USER_STATUS.AVAILABLE,
  },
  {
    userId: "16",
    profilePicture: null,
    displayName: "Patricia Robert",
    profession: "Nutritionniste",
    lastAppointment: null,
    status: USER_STATUS.UNAVAILABLE,
  },
  {
    userId: "17",
    profilePicture: null,
    displayName: "Quentin Petit",
    profession: "Pharmacien",
    lastAppointment: dayjs().subtract(9, "days"),
    status: USER_STATUS.AVAILABLE,
  },
  {
    userId: "18",
    profilePicture: null,
    displayName: "Rania Haddad",
    profession: "Rhumatologue",
    lastAppointment: dayjs().subtract(11, "days"),
    status: USER_STATUS.UNAVAILABLE,
  },
  {
    userId: "19",
    profilePicture: null,
    displayName: "Sébastien Leclerc",
    profession: "Gynécologue",
    lastAppointment: dayjs().subtract(3, "weeks"),
    status: USER_STATUS.AVAILABLE,
  },
  {
    userId: "20",
    profilePicture: null,
    displayName: "Thérèse Moulin",
    profession: "Endocrinologue",
    lastAppointment: null,
    status: USER_STATUS.UNAVAILABLE,
  },
  {
    userId: "21",
    profilePicture: null,
    displayName: "Ugo Martin",
    profession: "Pneumologue",
    lastAppointment: dayjs().subtract(1, "week"),
    status: USER_STATUS.AVAILABLE,
  },
  {
    userId: "22",
    profilePicture: null,
    displayName: "Valérie Dubois",
    profession: "Oncologue",
    lastAppointment: dayjs().subtract(5, "days"),
    status: USER_STATUS.UNAVAILABLE,
  },
  {
    userId: "23",
    profilePicture: null,
    displayName: "William Faure",
    profession: "Hématologue",
    lastAppointment: null,
    status: USER_STATUS.AVAILABLE,
  },
  {
    userId: "24",
    profilePicture: null,
    displayName: "Xavier Martin",
    profession: "Ophtalmologue",
    lastAppointment: dayjs().subtract(1, "month"),
    status: USER_STATUS.UNAVAILABLE,
  },
  {
    userId: "25",
    profilePicture: null,
    displayName: "Yasmine Abou",
    profession: "Néphrologue",
    lastAppointment: dayjs().subtract(2, "weeks"),
    status: USER_STATUS.AVAILABLE,
  },
  {
    userId: "26",
    profilePicture: null,
    displayName: "Zacharie Laurent",
    profession: "Chirurgien vasculaire",
    lastAppointment: null,
    status: USER_STATUS.UNAVAILABLE,
  },
  {
    userId: "27",
    profilePicture: null,
    displayName: "Zoé Dupuis",
    profession: "Chirurgien orthopédiste",
    lastAppointment: dayjs().subtract(2, "days"),
    status: USER_STATUS.AVAILABLE,
  },
  {
    userId: "28",
    profilePicture: null,
    displayName: "Aurélie Girard",
    profession: "Cardiologue",
    lastAppointment: null,
    status: USER_STATUS.UNAVAILABLE,
  },
  {
    userId: "29",
    profilePicture: null,
    displayName: "Baptiste Benamar",
    profession: "Neurologue",
    lastAppointment: dayjs().subtract(1, "week"),
    status: USER_STATUS.AVAILABLE,
  },
  {
    userId: "30",
    profilePicture: null,
    displayName: "Céline Bertin",
    profession: "Psychiatre",
    lastAppointment: dayjs().subtract(2, "days"),
    status: USER_STATUS.UNAVAILABLE,
  },
  {
    userId: "31",
    profilePicture: null,
    displayName: "Dylan Slaoui",
    profession: "Anesthésiste",
    lastAppointment: dayjs().subtract(5, "days"),
    status: USER_STATUS.AVAILABLE,
  },
  {
    userId: "32",
    profilePicture: null,
    displayName: "Emma Blanc",
    profession: "Radiologue",
    lastAppointment: null,
    status: USER_STATUS.UNAVAILABLE,
  },
  {
    userId: "33",
    profilePicture: null,
    displayName: "Florian Koné",
    profession: "Urologue",
    lastAppointment: dayjs().subtract(1, "month"),
    status: USER_STATUS.AVAILABLE,
  },
  {
    userId: "34",
    profilePicture: null,
    displayName: "Géraldine El Fassi",
    profession: "Pédiatre",
    lastAppointment: null,
    status: USER_STATUS.UNAVAILABLE,
  },
  {
    userId: "35",
    profilePicture: null,
    displayName: "Hugo Henry",
    profession: "Dermatologue",
    lastAppointment: dayjs().subtract(3, "days"),
    status: USER_STATUS.AVAILABLE,
  },
  {
    userId: "36",
    profilePicture: null,
    displayName: "Inès Robert",
    profession: "Nutritionniste",
    lastAppointment: null,
    status: USER_STATUS.UNAVAILABLE,
  },
  {
    userId: "37",
    profilePicture: null,
    displayName: "Jérémy Petit",
    profession: "Pharmacien",
    lastAppointment: dayjs().subtract(9, "days"),
    status: USER_STATUS.AVAILABLE,
  },
  {
    userId: "38",
    profilePicture: null,
    displayName: "Karine Haddad",
    profession: "Rhumatologue",
    lastAppointment: dayjs().subtract(11, "days"),
    status: USER_STATUS.UNAVAILABLE,
  },
  {
    userId: "39",
    profilePicture: null,
    displayName: "Léa Leclerc",
    profession: "Gynécologue",
    lastAppointment: dayjs().subtract(3, "weeks"),
    status: USER_STATUS.AVAILABLE,
  },
  {
    userId: "40",
    profilePicture: null,
    displayName: "Mathieu Moulin",
    profession: "Endocrinologue",
    lastAppointment: null,
    status: USER_STATUS.UNAVAILABLE,
  },
  {
    userId: "41",
    profilePicture: null,
    displayName: "Nathalie Martin",
    profession: "Pneumologue",
    lastAppointment: dayjs().subtract(1, "week"),
    status: USER_STATUS.AVAILABLE,
  },
  {
    userId: "42",
    profilePicture: null,
    displayName: "Olivier Dubois",
    profession: "Oncologue",
    lastAppointment: dayjs().subtract(5, "days"),
    status: USER_STATUS.UNAVAILABLE,
  },
  {
    userId: "43",
    profilePicture: null,
    displayName: "Paul Faure",
    profession: "Hématologue",
    lastAppointment: null,
    status: USER_STATUS.AVAILABLE,
  },
  {
    userId: "44",
    profilePicture: null,
    displayName: "Quentin Martin",
    profession: "Ophtalmologue",
    lastAppointment: dayjs().subtract(1, "month"),
    status: USER_STATUS.UNAVAILABLE,
  },
  {
    userId: "45",
    profilePicture: null,
    displayName: "Rania Abou",
    profession: "Néphrologue",
    lastAppointment: dayjs().subtract(2, "weeks"),
    status: USER_STATUS.AVAILABLE,
  },
]);

export const NUMBER_MORE_USERS = 10;
export const initialUsers = mock.slice(0, NUMBER_MORE_USERS);
