export enum DURATION {
  FIFTEEN_MINUTES = "00:15",
  THIRTY_MINUTES = "00:30",
  FOURTYFIVE_MINUTES = "00:45",
  ONE_HOUR = "01:00",
}

export enum DAY {
  MONDAY = "MONDAY",
  TUESDAY = "TUESDAY",
  WEDNESDAY = "WEDNESDAY",
  THURSDAY = "THURSDAY",
  FRIDAY = "FRIDAY",
  SATURDAY = "SATURDAY",
}

export enum PERIODICITY {
  WEEKLY = "WEEKLY",
  FORTNIGHTLY = "FORTNIGHTLY",
}

export enum GRID_STATE {
  OPEN = "OPEN",
  SUSPENDED = "SUSPENDED",
  CLOSED = "CLOSED",
}

export enum APPOINTMENT_STATE {
  CREATED = "CREATED",
  ACCEPTED = "ACCEPTED",
  REFUSED = "REFUSED",
  CANCELED = "CANCELED",
}

export enum CONFIRM_MODAL_TYPE {
  CANCEL_GRID_CREATION = "CANCEL_GRID_CREATION",
  CANCEL_GRID_EDIT = "CANCEL_GRID_EDIT",
  CONFIRM_GRID_EDIT = "CONFIRM_GRID_EDIT",
  REJECT_REQUEST = "REJECT_REQUEST",
  CANCEL_REQUEST = "CANCEL_REQUEST",
  CANCEL_APPOINTMENT = "CANCEL_APPOINTMENT",
  DELETE_GRID = "DELETE_GRID",
  SUSPEND_GRID = "SUSPEND_GRID",
  RESTORE_GRID = "RESTORE_GRID",
}

export enum TOAST_TYPE {
  CREATE_GRID = "CREATE_GRID",
  EDIT_GRID = "EDIT_GRID",
  ACCEPT_APPOINTMENT = "ACCEPT_APPOINTMENT",
  REJECT_APPOINTMENT = "REJECT_APPOINTMENT",
  CANCEL_APPOINTMENT = "CANCEL_APPOINTMENT",
  CANCEL_REQUEST = "CANCEL_REQUEST",
  DELETE_GRID = "DELETE_GRID",
  SUSPEND_GRID = "SUSPEND_GRID",
  RESTORE_GRID = "RESTORE_GRID",
}
