export enum SLOT_DURATION {
  FIVETEEN_MINUTES = "15 MIN",
  THIRTY_MINUTES = "30 MIN",
  FOURTYFIVE_MINUTES = "45 MIN",
  ONE_HOUR = "1 H",
}

export enum DAY {
  MONDAY = "MONDAY",
  TUESDAY = "TUESDAY",
  WEDNESDAY = "WEDNESDAY",
  THURSDAY = "THURSDAY",
  FRIDAY = "FRIDAY",
  SATURDAY = "SATURDAY",
}

export enum PERIODICITY {
  WEEKLY = 1,
  BIWEEKLY = 2,
}
