export enum DURATION {
  FIFTEEN_MINUTES = "00:15",
  THIRTY_MINUTES = "00:30",
  FOURTYFIVE_MINUTES = "00:45",
  ONE_HOUR = "01:00",
}

export enum DAY {
  MONDAY = "MONDAY",
  TUESDAY = "TUESDAY",
  WEDNESDAY = "WEDNESDAY",
  THURSDAY = "THURSDAY",
  FRIDAY = "FRIDAY",
  SATURDAY = "SATURDAY",
}

export enum PERIODICITY {
  WEEKLY = "WEEKLY",
  BIWEEKLY = "BIWEEKLY",
}

export enum GRID_STATE {
  OPEN = "OPEN",
  SUSPENDED = "SUSPENDED",
  CLOSED = "CLOSED",
}
